spring:
  application:
    name: config-server
  cloud:
    config:
      bootstrap:
          enabled: true
      server:
        git:
          uri: https://github.com/keshan200/SmartLogix-Configurations.git
          search-paths: platform,services
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services

server:
  port: 8888